---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: genesis-api
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: genesis
  policy:
    pattern: '^(v[0-9]+\\.[0-9]+\\.[0-9]+)$'